meta_product_name: 'Utopy hostel'
meta_title: 'Utopy hostel - Biarritz'
meta_description: 'Welcome to Utopy hostel in Biarritz. Affordable accommodation, perfect for travelling surfers and backpackers. Book now cheap dormitory beds near the ocean!'
meta_image: 'banner.png' # should exist in `app/assets/images/`
